import CompanyPage from "@/components/CompanyPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Supreme Embellishment Ltd.",
  description: "Bangladesh's leading printing & embroidery facility — 62,000 sq ft, 520 employees, 80,000 pcs/day with in-house ETP.",
};

export default function EmbellishmentPage() {
  return (
    <CompanyPage
      category="Printing & Embroidery"
      name="Supreme Embellishment Ltd."
      tagline="Bringing garments to life — world-class printing and embroidery services at scale, with a commitment to responsible production."
      overview="Supreme Embellishment Ltd. is one of Bangladesh's largest and most capable garment embellishment facilities. Spread across 62,000 square feet of purpose-built production space, we employ 520 skilled workers and operate a comprehensive range of printing and embroidery technologies. Our daily output of 80,000 pieces makes us a primary embellishment partner for garment manufacturers across the country. Beyond sheer scale, what sets us apart is our commitment to responsible operations — we operate a fully functional Effluent Treatment Plant (ETP) to ensure that our production processes meet environmental standards and do not harm our surrounding communities."
      stats={[
        { number: "62K", label: "Sq Ft Facility" },
        { number: "520", label: "Employees" },
        { number: "80K", label: "Pcs/Day" },
        { number: "ETP", label: "Certified" },
      ]}
      sections={[
        {
          heading: "Screen Printing",
          body: [
            "High-volume screen printing for t-shirts, polos, jerseys, and all garment types — available in plastisol, water-based, and discharge inks.",
            "Multi-color registration with tight tolerances ensures consistent results across every unit in a production run.",
          ],
        },
        {
          heading: "Digital & Sublimation",
          body: [
            "State-of-the-art digital and sublimation printing for photographic detail, gradients, and all-over print designs.",
            "Ideal for sportswear, activewear, and fashion garments requiring vibrant, detailed artwork.",
          ],
        },
        {
          heading: "Embroidery",
          body: [
            "Computer-controlled embroidery machines capable of executing complex, multi-color designs with precision.",
            "From chest logos and sleeve patches to full back embroidery — we handle it all with speed and accuracy.",
          ],
        },
        {
          heading: "Heat Transfer & Speciality",
          body: [
            "Vinyl heat transfer, reflective printing, puff printing, foil, and specialty effects for premium brand requirements.",
            "Our R&D team stays current with evolving print technologies to offer our clients the latest in embellishment.",
          ],
        },
        {
          heading: "ETP — Environmental Commitment",
          body: [
            "Our Effluent Treatment Plant (ETP) processes all wastewater generated by printing operations before it is discharged.",
            "We are one of the few embellishment facilities in Bangladesh with a fully operational ETP — a point of pride and a commitment to responsible production.",
          ],
        },
        {
          heading: "Capacity & Scale",
          body: [
            "80,000 pieces per day across a 62,000 sq ft facility — designed for high-volume, consistent output.",
            "520 employees work across day and night shifts to meet tight delivery schedules for Bangladesh's top garment exporters.",
          ],
        },
      ]}
      highlights={[
        "80,000 pieces/day production capacity",
        "62,000 sq ft purpose-built embellishment facility",
        "520 skilled employees across all departments",
        "In-house Effluent Treatment Plant (ETP) — environmentally compliant",
        "Screen, digital, sublimation, and heat transfer printing",
        "Multi-head computerized embroidery machines",
        "Tight turnaround times with high-volume handling",
        "Specialty effects: puff, foil, reflective, and discharge",
      ]}
    />
  );
}
